version: '3'
services:
    server:
        container_name: mblog-server
        image: guanglei/mblog:latest
        build: .
        working_dir: /app/mblog
        environment:
            TZ: Asia/Shanghai
        ports:
            - "8080:8080"
        volumes:
            - /data/mblog/storage:/app/mblog/storage
            - /data/mblog/logs:/app/mblog/logs
        restart: always